# Generated by Django 3.2.9 on 2021-11-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('confirmed', models.PositiveIntegerField()),
                ('recovered', models.PositiveIntegerField()),
                ('critical', models.PositiveIntegerField()),
                ('deaths', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('lastChange', models.DateTimeField()),
                ('lastUpdate', models.DateTimeField()),
            ],
        ),
    ]
