# Generated by Django 3.2.9 on 2021-11-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidData_app', '0003_auto_20211115_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='update',
            new_name='updated',
        ),
    ]
